import { type Rotation } from './orientation';
import { SQRT2_2 } from './vec';

// A position in row/col space (the station-local cell coordinate system,
// where one unit equals one stop diameter).
export type RowCol = { row: number; col: number };

/** Floating-point epsilon for cell-equality comparisons — row/col are not
 *  integer (diagonal lattice steps are ±√2/2). */
export const CELL_EPS = 1e-4;

export const sameCell = (a: RowCol, b: RowCol): boolean =>
  Math.abs(a.row - b.row) < CELL_EPS && Math.abs(a.col - b.col) < CELL_EPS;

// Lattice basis around the origin in (row, col) space:
//
// - 'orthogonal': integer (i, j) cardinal lattice. Cardinals sit at
//   distance 1; integer diagonals (±1, ±1) sit at distance √2 (corner-touch
//   with a visible gap).
//
// - 'diagonal': the same lattice rotated 45° — generated by integer
//   combinations of the NE = (-√2/2, +√2/2) and SE = (+√2/2, +√2/2) unit
//   vectors. Tangent diagonals at distance 1; "purely cardinal" positions
//   like (0, ±√2) and (±√2, 0) (reached by NE+SE, NE−SE, etc.) at distance
//   √2 and beyond. Disjoint from the orthogonal lattice except at the
//   origin.
export type LatticeBasis = 'orthogonal' | 'diagonal';

/**
 * The integer coefficients of the lattice point nearest `d`, a delta in the
 * same (row, col) space the offsets come back in. Both bases are ORTHONORMAL —
 * 'orthogonal' trivially, and 'diagonal' because NE and SE are perpendicular
 * unit vectors — so rounding each coefficient on its own lands on the nearest
 * point, with no lattice search.
 */
function nearestCoeffs(basis: LatticeBasis, d: RowCol): [a: number, b: number] {
  if (basis === 'orthogonal') return [Math.round(d.row), Math.round(d.col)];
  // Inverting the diagonal generators below: row = (b − a)·√2/2 and
  // col = (a + b)·√2/2, so a = (col − row) / (2·√2/2) and b = (col + row) / (2·√2/2).
  return [Math.round((d.col - d.row) / (2 * SQRT2_2)), Math.round((d.col + d.row) / (2 * SQRT2_2))];
}

/**
 * A (2·radius + 1)² window of offsets in the chosen basis, excluding the
 * ORIGIN. Output is in the same coordinate system as the input — caller is
 * responsible for any rotation projection if the lattice was generated in one
 * frame and must be applied in another.
 *
 * `center` slides the window onto the lattice point nearest it (an off-lattice
 * center snaps, which is how a drifted node heals back onto the lattice)
 * without moving the lattice itself: same pitch, same phase, so slots stay
 * where the origin's lattice puts them. The origin exclusion does NOT travel
 * with the window — a slid window that reaches back over the origin still
 * omits it, and offers its own center like any other cell.
 */
export function latticeOffsets(basis: LatticeBasis, radius: number, center?: RowCol): RowCol[] {
  const out: RowCol[] = [];
  // Fold the shift into the loop bounds rather than adding it to the emitted
  // cells: every offset then still comes out of the SAME single multiplication
  // that keeps it exactly an integer or exactly k·√2/2 (see below).
  const [ca, cb] = center ? nearestCoeffs(basis, center) : [0, 0];
  for (let a = ca - radius; a <= ca + radius; a++) {
    for (let b = cb - radius; b <= cb + radius; b++) {
      if (a === 0 && b === 0) continue;
      if (basis === 'orthogonal') {
        out.push({ row: a, col: b });
      } else {
        // a·NE + b·SE with NE = (-√2/2, +√2/2), SE = (+√2/2, +√2/2):
        //   dRow = a·(-√2/2) + b·(+√2/2) = (b - a)·√2/2
        //   dCol = a·(+√2/2) + b·(+√2/2) = (a + b)·√2/2
        out.push({ row: (b - a) * SQRT2_2, col: (a + b) * SQRT2_2 });
      }
    }
  }
  return out;
}

const OTHER_BASIS: Record<LatticeBasis, LatticeBasis> = {
  orthogonal: 'diagonal',
  diagonal: 'orthogonal',
};

/**
 * The same lattice as `latticeOffsets`, but chosen in SCREEN terms and returned
 * in the LOCAL frame of an element rotated by `rotation` 45°-steps clockwise
 * (an SVG with `transform: rotate(rotation·45deg)`). Callers pick the basis the
 * user sees — the station editor's unshifted lattice is screen-orthogonal at
 * every rotation — and get cells they can store.
 *
 * The two bases are each other's 45° rotation, and each is closed under 90°
 * rotation, so projecting one into a rotated frame never leaves the pair: a
 * quarter turn maps a lattice onto ITSELF (a relabeling of the same offsets),
 * and an eighth turn maps each basis onto the other. Choosing the basis is
 * therefore the whole projection — there is no rotation left to apply.
 *
 * That matters for more than tidiness. Actually rotating the offsets cannot be
 * made exact: generating the diagonal basis scales by √2/2, turning 45° scales
 * by √2/2 again, and √2/2 · √2/2 is 0.5000000000000001, so a slot one cell from
 * its anchor came back as 1.0000000000000002. `computeGhosts` adds these to a
 * station's anchor cell and the sum is committed and saved, so that drift became
 * a permanent coordinate in the document. Picking the basis has no arithmetic in
 * it at all, and every cell it yields is exactly an integer or exactly an
 * integer multiple of √2/2.
 */
export function localLatticeOffsets(
  basis: LatticeBasis,
  radius: number,
  rotation: Rotation,
  center?: RowCol,
): RowCol[] {
  return latticeOffsets(rotation % 2 === 0 ? basis : OTHER_BASIS[basis], radius, center);
}
