import { rotateBy, type Rotation } from './orientation';
import { SQRT2_2 } from './vec';

// A position in row/col space (the StopGrid's coordinate system, where one
// unit equals one stop diameter).
export type RowCol = { row: number; col: number };

// Lattice basis around the origin in (row, col) space:
//
// - 'orthogonal': integer (i, j) cardinal lattice. Cardinals sit at
//   distance 1; integer diagonals (±1, ±1) sit at distance √2 (corner-touch
//   with a visible gap).
//
// - 'diagonal': the same lattice rotated 45° — generated by integer
//   combinations of the NE = (-√2/2, +√2/2) and SE = (+√2/2, +√2/2) unit
//   vectors. Tangent diagonals at distance 1; "purely cardinal" positions
//   like (0, ±√2) and (±√2, 0) (reached by NE+SE, NE−SE, etc.) at distance
//   √2 and beyond. Disjoint from the orthogonal lattice except at the
//   origin.
export type LatticeBasis = 'orthogonal' | 'diagonal';

/**
 * (2·radius + 1)² − 1 offsets centered on (0, 0), excluding the origin,
 * in the chosen basis. Output is in the same coordinate system as the
 * input — caller is responsible for any rotation projection if the lattice
 * was generated in one frame and must be applied in another.
 */
export function latticeOffsets(basis: LatticeBasis, radius: number): RowCol[] {
  const out: RowCol[] = [];
  for (let a = -radius; a <= radius; a++) {
    for (let b = -radius; b <= radius; b++) {
      if (a === 0 && b === 0) continue;
      if (basis === 'orthogonal') {
        out.push({ row: a, col: b });
      } else {
        // a·NE + b·SE with NE = (-√2/2, +√2/2), SE = (+√2/2, +√2/2):
        //   dRow = a·(-√2/2) + b·(+√2/2) = (b - a)·√2/2
        //   dCol = a·(+√2/2) + b·(+√2/2) = (a + b)·√2/2
        out.push({ row: (b - a) * SQRT2_2, col: (a + b) * SQRT2_2 });
      }
    }
  }
  return out;
}

/**
 * Project screen-frame offsets into the local frame of an element rotated
 * by `rotation` 45°-steps clockwise (i.e. an SVG with CSS
 * `transform: rotate(rotation·45deg)`). Applies the INVERSE rotation so that
 * the caller can generate a lattice in screen-aligned terms and have it
 * paint correctly inside the rotated SVG.
 */
export function projectScreenToLocal(offsets: RowCol[], rotation: Rotation): RowCol[] {
  if (rotation === 0) return offsets;
  const inv = ((8 - rotation) % 8) as Rotation;
  return offsets.map((o) => {
    // rotateBy operates on (x, y) where x = col, y = row.
    const p = rotateBy({ x: o.col, y: o.row }, inv);
    return { row: p.y, col: p.x };
  });
}
