// Station names from three real-world transit systems, used as random
// defaults when the user adds a new station. Sources (fetched once):
//   - BART: en.wikipedia.org/wiki/List_of_Bay_Area_Rapid_Transit_stations
//   - London Underground: en.wikipedia.org/wiki/List_of_London_Underground_stations
//   - MTR (Hong Kong): en.wikipedia.org/wiki/List_of_MTR_stations
// Lists are not exhaustive and include light cleanup (deduped, dropped
// closed/disambiguation-only entries). Order is alphabetical per system.

const BART_STATIONS: string[] = [
  '12th Street Oakland',
  '16th Street Mission',
  '19th Street Oakland',
  '24th Street Mission',
  'Antioch',
  'Ashby',
  'Balboa Park',
  'Bay Fair',
  'Berryessa',
  'Castro Valley',
  'Civic Center',
  'Coliseum',
  'Colma',
  'Concord',
  'Daly City',
  'Downtown Berkeley',
  'Dublin/Pleasanton',
  'El Cerrito del Norte',
  'El Cerrito Plaza',
  'Embarcadero',
  'Fremont',
  'Fruitvale',
  'Glen Park',
  'Hayward',
  'Lafayette',
  'Lake Merritt',
  'MacArthur',
  'Millbrae',
  'Milpitas',
  'Montgomery Street',
  'North Berkeley',
  'North Concord',
  'Oakland Airport',
  'Orinda',
  'Pittsburg/Bay Point',
  'Pittsburg Center',
  'Pleasant Hill',
  'Powell Street',
  'Richmond',
  'Rockridge',
  'San Bruno',
  'SFO',
  'San Leandro',
  'South Hayward',
  'South San Francisco',
  'Union City',
  'Walnut Creek',
  'Warm Springs',
  'West Dublin',
  'West Oakland',
];

const LONDON_STATIONS: string[] = [
  'Acton Town',
  'Aldgate',
  'Aldgate East',
  'Alperton',
  'Amersham',
  'Angel',
  'Archway',
  'Arnos Grove',
  'Arsenal',
  'Baker Street',
  'Balham',
  'Bank',
  'Barbican',
  'Barking',
  'Barkingside',
  'Barons Court',
  'Bayswater',
  'Becontree',
  'Belsize Park',
  'Bermondsey',
  'Bethnal Green',
  'Blackfriars',
  'Blackhorse Road',
  'Bond Street',
  'Borough',
  'Boston Manor',
  'Bounds Green',
  'Brent Cross',
  'Brixton',
  'Bromley-by-Bow',
  'Buckhurst Hill',
  'Burnt Oak',
  'Caledonian Road',
  'Camden Town',
  'Canada Water',
  'Canary Wharf',
  'Canning Town',
  'Cannon Street',
  'Canons Park',
  'Chalfont & Latimer',
  'Chalk Farm',
  'Chancery Lane',
  'Charing Cross',
  'Chesham',
  'Chigwell',
  'Chiswick Park',
  'Chorleywood',
  'Clapham Common',
  'Clapham North',
  'Clapham South',
  'Cockfosters',
  'Colindale',
  'Colliers Wood',
  'Covent Garden',
  'Croxley',
  'Dagenham East',
  'Dagenham Heathway',
  'Debden',
  'Dollis Hill',
  'Ealing Broadway',
  'Ealing Common',
  "Earl's Court",
  'East Acton',
  'East Finchley',
  'East Ham',
  'East Putney',
  'Eastcote',
  'Edgware',
  'Edgware Road',
  'Elephant & Castle',
  'Elm Park',
  'Embankment',
  'Epping',
  'Euston',
  'Euston Square',
  'Fairlop',
  'Farringdon',
  'Finchley Central',
  'Finchley Road',
  'Finsbury Park',
  'Fulham Broadway',
  'Gants Hill',
  'Gloucester Road',
  'Golders Green',
  'Goldhawk Road',
  'Goodge Street',
  'Grange Hill',
  'Great Portland Street',
  'Green Park',
  'Greenford',
  'Gunnersbury',
  'Hainault',
  'Hammersmith',
  'Hampstead',
  'Hanger Lane',
  'Harlesden',
  'Harrow & Wealdstone',
  'Harrow-on-the-Hill',
  'Hatton Cross',
  'Heathrow Terminals 2 & 3',
  'Heathrow Terminal 4',
  'Heathrow Terminal 5',
  'Hendon Central',
  'High Barnet',
  'Highbury & Islington',
  'Highgate',
  'High Street Kensington',
  'Hillingdon',
  'Holborn',
  'Holland Park',
  'Holloway Road',
  'Hornchurch',
  'Hounslow Central',
  'Hounslow East',
  'Hounslow West',
  'Hyde Park Corner',
  'Ickenham',
  'Kennington',
  'Kensal Green',
  'Kensington (Olympia)',
  'Kentish Town',
  'Kew Gardens',
  'Kilburn',
  'Kilburn Park',
  'Kingsbury',
  'Knightsbridge',
  'Ladbroke Grove',
  'Lambeth North',
  'Lancaster Gate',
  'Latimer Road',
  'Leicester Square',
  'Leyton',
  'Leytonstone',
  'Liverpool Street',
  'London Bridge',
  'Loughton',
  'Maida Vale',
  'Manor House',
  'Mansion House',
  'Marble Arch',
  'Marylebone',
  'Mile End',
  'Mill Hill East',
  'Monument',
  'Moor Park',
  'Moorgate',
  'Mornington Crescent',
  'Neasden',
  'Newbury Park',
  'North Acton',
  'North Ealing',
  'North Greenwich',
  'North Harrow',
  'North Wembley',
  'Northfields',
  'Northolt',
  'Notting Hill Gate',
  'Oakwood',
  'Old Street',
  'Osterley',
  'Oval',
  'Oxford Circus',
  'Paddington',
  'Park Royal',
  'Parsons Green',
  'Perivale',
  'Piccadilly Circus',
  'Pimlico',
  'Pinner',
  'Plaistow',
  'Preston Road',
  "Queen's Park",
  'Queensbury',
  'Queensway',
  'Ravenscourt Park',
  'Rayners Lane',
  'Redbridge',
  "Regent's Park",
  'Rickmansworth',
  'Roding Valley',
  'Royal Oak',
  'Ruislip',
  'Ruislip Gardens',
  'Ruislip Manor',
  'Russell Square',
  "St James's Park",
  "St John's Wood",
  "St Paul's",
  'Seven Sisters',
  'Shepherd\'s Bush',
  'Sloane Square',
  'Snaresbrook',
  'South Ealing',
  'South Harrow',
  'South Kensington',
  'South Ruislip',
  'South Wimbledon',
  'South Woodford',
  'Southfields',
  'Southgate',
  'Southwark',
  'Stamford Brook',
  'Stanmore',
  'Stepney Green',
  'Stockwell',
  'Stonebridge Park',
  'Stratford',
  'Sudbury Hill',
  'Sudbury Town',
  'Swiss Cottage',
  'Temple',
  'Theydon Bois',
  'Tooting Bec',
  'Tooting Broadway',
  'Tottenham Court Road',
  'Tottenham Hale',
  'Totteridge & Whetstone',
  'Tower Hill',
  'Tufnell Park',
  'Turnham Green',
  'Turnpike Lane',
  'Upminster',
  'Upminster Bridge',
  'Upney',
  'Upton Park',
  'Uxbridge',
  'Vauxhall',
  'Victoria',
  'Walthamstow Central',
  'Wanstead',
  'Warren Street',
  'Warwick Avenue',
  'Waterloo',
  'Watford',
  'Wembley Central',
  'Wembley Park',
  'West Acton',
  'West Brompton',
  'West Finchley',
  'West Ham',
  'West Hampstead',
  'West Harrow',
  'West Kensington',
  'West Ruislip',
  'Westbourne Park',
  'Westminster',
  'White City',
  'Whitechapel',
  'Willesden Green',
  'Willesden Junction',
  'Wimbledon',
  'Wimbledon Park',
  'Wood Green',
  'Woodford',
  'Woodside Park',
];

const MTR_STATIONS: string[] = [
  'Admiralty',
  'AsiaWorld–Expo',
  'Austin',
  'Causeway Bay',
  'Central',
  'Chai Wan',
  'Che Kung Temple',
  'Cheung Sha Wan',
  'Choi Hung',
  'City One',
  'Diamond Hill',
  'Disneyland Resort',
  'East Tsim Sha Tsui',
  'Exhibition Centre',
  'Fanling',
  'Fo Tan',
  'Fortress Hill',
  'Hang Hau',
  'Heng Fa Chuen',
  'Heng On',
  'Hin Keng',
  'HKU',
  'Ho Man Tin',
  'Hong Kong',
  'Hung Hom',
  'Jordan',
  'Kai Tak',
  'Kam Sheung Road',
  'Kennedy Town',
  'Kowloon',
  'Kowloon Bay',
  'Kowloon Tong',
  'Kwai Fong',
  'Kwai Hing',
  'Kwun Tong',
  'Lai Chi Kok',
  'Lai King',
  'Lam Tin',
  'Lei Tung',
  'Lo Wu',
  'LOHAS Park',
  'Lok Fu',
  'Lok Ma Chau',
  'Long Ping',
  'Ma On Shan',
  'Mei Foo',
  'Mong Kok',
  'Mong Kok East',
  'Nam Cheong',
  'Ngau Tau Kok',
  'North Point',
  'Ocean Park',
  'Olympic',
  'Po Lam',
  'Prince Edward',
  'Quarry Bay',
  'Racecourse',
  'Sai Wan Ho',
  'Sai Ying Pun',
  'Sha Tin',
  'Sha Tin Wai',
  'Sham Shui Po',
  'Shau Kei Wan',
  'Shek Kip Mei',
  'Shek Mun',
  'Sheung Shui',
  'Sheung Wan',
  'Siu Hong',
  'South Horizons',
  'Sunny Bay',
  'Sung Wong Toi',
  'Tai Koo',
  'Tai Po Market',
  'Tai Shui Hang',
  'Tai Wai',
  'Tai Wo',
  'Tai Wo Hau',
  'Tin Hau',
  'Tin Shui Wai',
  'Tiu Keng Leng',
  'To Kwa Wan',
  'Tseung Kwan O',
  'Tsim Sha Tsui',
  'Tsing Yi',
  'Tsuen Wan',
  'Tsuen Wan West',
  'Tuen Mun',
  'Tung Chung',
  'University',
  'Wan Chai',
  'Whampoa',
  'Wong Chuk Hang',
  'Wong Tai Sin',
  'Wu Kai Sha',
  'Yau Ma Tei',
  'Yau Tong',
  'Yuen Long',
];

const ALL_NAMES: string[] = [...BART_STATIONS, ...LONDON_STATIONS, ...MTR_STATIONS];

export function randomStationName(): string {
  return ALL_NAMES[Math.floor(Math.random() * ALL_NAMES.length)];
}
