import { useEffect, useRef, useState } from 'react';
import type { StopOrientation } from '../../model/types';

type GridStation = {
  rotation: number;
  stops: { lineId: string; row: number; col: number; orientation: StopOrientation }[];
  label: { row: number; col: number; rotation: number };
};

const ORIENTATION_GLYPH: Record<StopOrientation, string> = {
  'auto-vertical': '↕',
  'auto-ne-sw': '⤢',
  'auto-horizontal': '↔',
  'auto-nw-se': '⤡',
};

// Display pitch (inspector-local pixels per unit in row/col space).
// Circle radius = pitch / 2 so two nodes at unit distance in (row, col) space
// are tangent.
const PITCH = 22;
const RADIUS = PITCH / 2;
const DRAG_THRESHOLD_PX = 4;

// Two grids the editor can offer around the anchor — both are full 2D
// lattices, just expressed in different bases:
//
// - ORTHOGONAL (default): integer (i, j) cardinal lattice. Cardinals at
//   distance 1, integer diagonals at distance √2 (corner-touch with a gap).
//
// - DIAGONAL (shift): the same lattice rotated 45°, generated by integer
//   combinations of the NE and SE unit vectors. Tangent diagonals at
//   distance 1, "purely cardinal" positions at distance √2 (reached by
//   NE + SE = east, etc.) and beyond. Has NO overlap with the orthogonal
//   lattice except at the anchor itself — picking a mode picks which
//   complementary set of positions you want.
//
// Both lattices span (a, b) ∈ [-GRID_RADIUS, +GRID_RADIUS]² minus the
// anchor → 24 candidate positions each at GRID_RADIUS = 2.
const HALF_SQRT2 = Math.SQRT1_2;
const GRID_RADIUS = 2;

// Floating-point epsilon for cell-equality comparisons (row/col are no longer
// constrained to integers — diagonals use ±√2/2).
const EPS = 1e-4;

// Padding (in row/col units) so the viewBox always has room for any reachable
// ghost regardless of drag mode. The diagonal lattice's farthest points are
// at GRID_RADIUS · √2 along the cardinal axes (e.g. anchor + 2·NE + 2·SE =
// 2√2 east), so pad up to that with a unit ceil.
const VIEW_PAD = Math.ceil(GRID_RADIUS * Math.SQRT2);

// Cursor-to-ghost snap radius (in row/col units). Inside this radius the
// nearest ghost wins; outside, no drop target.
const GHOST_SNAP_RADIUS = 1.0;
// Cursor-to-stop swap radius — must be physically on the stop circle to
// register a swap (so a tangent ghost right next to a stop doesn't get
// hijacked by a distant cursor).
const STOP_SWAP_RADIUS = 0.6;

type DragSource =
  | { kind: 'stop'; lineId: string; row: number; col: number }
  | { kind: 'label'; row: number; col: number };

type TargetKind = 'ghost' | 'stop';

type DragTarget = { row: number; col: number; kind: TargetKind };

type DragState = {
  source: DragSource;
  startX: number;
  startY: number;
  isDragging: boolean;
  // Cursor in (row, col) space — populated once the drag threshold is crossed.
  cursor: { row: number; col: number } | null;
};

const dist = (a: { row: number; col: number }, b: { row: number; col: number }): number =>
  Math.hypot(a.row - b.row, a.col - b.col);

const sameCell = (a: { row: number; col: number }, b: { row: number; col: number }): boolean =>
  Math.abs(a.row - b.row) < EPS && Math.abs(a.col - b.col) < EPS;

const fmt = (n: number) => n.toFixed(6);

export function StopGrid({
  station,
  lines,
  selectedLineId,
  labelSelected,
  onSelectStop,
  onSelectLabel,
  onRotateStop,
  onRotateLabel,
  onMoveStop,
  onMoveLabel,
}: {
  station: GridStation;
  lines: Record<string, { color: string; service: string }>;
  selectedLineId: string | null;
  labelSelected: boolean;
  onSelectStop: (lineId: string | null) => void;
  onSelectLabel: () => void;
  onRotateStop: (lineId: string) => void;
  onRotateLabel: () => void;
  onMoveStop: (lineId: string, dRow: number, dCol: number) => void;
  onMoveLabel: (dRow: number, dCol: number) => void;
}) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const [drag, setDrag] = useState<DragState | null>(null);
  const [shiftHeld, setShiftHeld] = useState(false);
  const stops = station.stops;
  const label = station.label;

  // Track Shift globally while a drag is in progress. The window-level
  // keydown/keyup handler catches toggles even if the cursor leaves the
  // editor. Initial state and per-move state are also read off the pointer
  // event itself (e.shiftKey) — important because if Shift was already held
  // when the drag started, no fresh keydown fires after the listeners attach.
  useEffect(() => {
    if (!drag?.isDragging) return;
    const sync = (e: KeyboardEvent) => setShiftHeld(e.shiftKey);
    window.addEventListener('keydown', sync);
    window.addEventListener('keyup', sync);
    return () => {
      window.removeEventListener('keydown', sync);
      window.removeEventListener('keyup', sync);
      setShiftHeld(false);
    };
  }, [drag?.isDragging]);

  const sourceCell = drag ? { row: drag.source.row, col: drag.source.col } : null;

  const nodesAll: { row: number; col: number; kind: 'stop' | 'label' }[] = [
    ...stops.map((s) => ({ row: s.row, col: s.col, kind: 'stop' as const })),
    { row: label.row, col: label.col, kind: 'label' as const },
  ];
  // Non-source nodes — candidates for "anchor" and the things ghost slots
  // must not collide with.
  const otherNodes = sourceCell ? nodesAll.filter((n) => !sameCell(n, sourceCell)) : nodesAll;

  // Anchor = nearest non-source node to the cursor (only while dragging).
  let anchor: { row: number; col: number; kind: 'stop' | 'label' } | null = null;
  if (drag?.isDragging && drag.cursor && otherNodes.length > 0) {
    let best = Infinity;
    for (const n of otherNodes) {
      const d = dist(drag.cursor, n);
      if (d < best) {
        best = d;
        anchor = n;
      }
    }
  }

  // Build the ghost set for the active mode.
  //
  // Orthogonal (default): (a, b) → (dRow = a, dCol = b) — cardinal basis.
  // Diagonal (shift): (a, b) → a·NE + b·SE — 45°-rotated basis. The two
  // lattices are complementary; positions don't overlap.
  //
  // The SVG wrapper applies CSS rotate(station.rotation·45°), so when
  // rotation is odd, the local-frame orthogonal lattice paints as on-screen
  // diagonal (and vice versa). Swap which lattice each mode generates so the
  // user sees an on-screen orthogonal grid by default and an on-screen
  // diagonal grid on Shift, regardless of station rotation. The (dRow, dCol)
  // we hand to onMoveStop is still in local frame — only the visual
  // selection rule swaps.
  const oddStationRotation = station.rotation % 2 === 1;
  const useDiagonalLattice = shiftHeld !== oddStationRotation;
  const ghosts: { row: number; col: number }[] = [];
  if (anchor) {
    const offsets: { dRow: number; dCol: number }[] = [];
    for (let a = -GRID_RADIUS; a <= GRID_RADIUS; a++) {
      for (let b = -GRID_RADIUS; b <= GRID_RADIUS; b++) {
        if (a === 0 && b === 0) continue;
        if (useDiagonalLattice) {
          // a·NE + b·SE where NE = (-√2/2, +√2/2), SE = (+√2/2, +√2/2).
          offsets.push({ dRow: (b - a) * HALF_SQRT2, dCol: (a + b) * HALF_SQRT2 });
        } else {
          offsets.push({ dRow: a, dCol: b });
        }
      }
    }
    for (const o of offsets) {
      const g = { row: anchor.row + o.dRow, col: anchor.col + o.dCol };
      let overlap = false;
      for (const n of otherNodes) {
        if (sameCell(n, anchor)) continue;
        // Ghosts at distance < 1 from any other node overlap visually.
        // Tangent (distance == 1) is allowed.
        if (dist(g, n) < 1 - EPS) {
          overlap = true;
          break;
        }
      }
      if (overlap) continue;
      ghosts.push(g);
    }
  }

  // Derive the drop target from cursor position. Two tiers:
  //   1. Swap: cursor lies INSIDE a non-source stop's circle → swap target.
  //      Only meaningful for stop sources.
  //   2. Ghost: nearest ghost within GHOST_SNAP_RADIUS of cursor.
  let over: DragTarget | null = null;
  if (drag?.isDragging && drag.cursor) {
    if (drag.source.kind === 'stop') {
      for (const s of stops) {
        if (s.lineId === drag.source.lineId) continue;
        if (dist(drag.cursor, s) < STOP_SWAP_RADIUS) {
          over = { row: s.row, col: s.col, kind: 'stop' };
          break;
        }
      }
    }
    if (!over) {
      let bestDist = GHOST_SNAP_RADIUS;
      let best: { row: number; col: number } | null = null;
      for (const g of ghosts) {
        const d = dist(drag.cursor, g);
        if (d < bestDist) {
          bestDist = d;
          best = g;
        }
      }
      if (best) over = { row: best.row, col: best.col, kind: 'ghost' };
    }
  }

  // ViewBox padding handles every reachable ghost regardless of mode.
  const rows = nodesAll.map((c) => c.row);
  const cols = nodesAll.map((c) => c.col);
  const minRow = Math.min(...rows) - VIEW_PAD;
  const maxRow = Math.max(...rows) + VIEW_PAD;
  const minCol = Math.min(...cols) - VIEW_PAD;
  const maxCol = Math.max(...cols) + VIEW_PAD;
  const vbX = (minCol - 0.5) * PITCH;
  const vbY = (minRow - 0.5) * PITCH;
  const vbW = (maxCol - minCol + 1) * PITCH;
  const vbH = (maxRow - minRow + 1) * PITCH;

  // Rotation-tolerant outer wrapper — controls below the editor don't reflow
  // when station.rotation changes (every 45° step).
  const wrapSize = Math.max(vbW, vbH, (vbW + vbH) * Math.SQRT1_2);
  const angleDeg = station.rotation * 45;

  // Convert screen coords → SVG user-coords → (row, col). Accounts for the
  // CSS rotation on the SVG wrapper via getScreenCTM.
  const cursorRowCol = (clientX: number, clientY: number): { row: number; col: number } | null => {
    const svg = svgRef.current;
    if (!svg) return null;
    const ctm = svg.getScreenCTM();
    if (!ctm) return null;
    const pt = svg.createSVGPoint();
    pt.x = clientX;
    pt.y = clientY;
    const sp = pt.matrixTransform(ctm.inverse());
    return { row: sp.y / PITCH, col: sp.x / PITCH };
  };

  const startDrag = (e: React.PointerEvent, source: DragSource) => {
    svgRef.current?.setPointerCapture(e.pointerId);
    // Seed shiftHeld from the pointer event — if Shift is already held when
    // the drag begins, no keydown fires after our listeners attach, so we'd
    // otherwise miss it.
    setShiftHeld(e.shiftKey);
    setDrag({
      source,
      startX: e.clientX,
      startY: e.clientY,
      isDragging: false,
      cursor: null,
    });
  };

  const onSvgPointerMove = (e: React.PointerEvent) => {
    if (!drag) return;
    const dx = e.clientX - drag.startX;
    const dy = e.clientY - drag.startY;
    const isDragging = drag.isDragging || Math.hypot(dx, dy) > DRAG_THRESHOLD_PX;
    const cursor = isDragging ? cursorRowCol(e.clientX, e.clientY) : null;
    // Re-read shift on every move — handles the case where the user pressed
    // Shift before starting the drag (no keydown to catch) and also keeps
    // state in sync if a window keyup fires elsewhere.
    if (e.shiftKey !== shiftHeld) setShiftHeld(e.shiftKey);
    if (
      isDragging !== drag.isDragging ||
      cursor?.row !== drag.cursor?.row ||
      cursor?.col !== drag.cursor?.col
    ) {
      setDrag({ ...drag, isDragging, cursor });
    }
  };

  const onSvgPointerUp = () => {
    if (!drag) return;
    if (drag.isDragging) {
      // For drops, validate against the same logic that drove the highlight.
      // Disallow stop sources dropping on the label (the over=stop case
      // already excludes labels), and disallow label sources from triggering
      // swap (over=stop only fires for stop sources above).
      if (over) {
        const dRow = over.row - drag.source.row;
        const dCol = over.col - drag.source.col;
        if (Math.abs(dRow) > EPS || Math.abs(dCol) > EPS) {
          if (drag.source.kind === 'stop') onMoveStop(drag.source.lineId, dRow, dCol);
          else onMoveLabel(dRow, dCol);
        }
      }
    } else {
      if (drag.source.kind === 'stop') onSelectStop(drag.source.lineId);
      else onSelectLabel();
    }
    setDrag(null);
  };

  const onSvgPointerCancel = () => setDrag(null);

  return (
    <div style={{ position: 'relative', width: wrapSize, height: wrapSize }}>
      <svg
        ref={svgRef}
        viewBox={`${vbX} ${vbY} ${vbW} ${vbH}`}
        width={vbW}
        height={vbH}
        onPointerMove={onSvgPointerMove}
        onPointerUp={onSvgPointerUp}
        onPointerCancel={onSvgPointerCancel}
        style={{
          position: 'absolute',
          left: '50%',
          top: '50%',
          transform: `translate(-50%, -50%) rotate(${angleDeg}deg)`,
          overflow: 'visible',
          touchAction: 'none',
          userSelect: 'none',
          WebkitUserSelect: 'none',
        }}
      >
        {/* Background — clicks deselect. */}
        <rect
          x={vbX}
          y={vbY}
          width={vbW}
          height={vbH}
          fill="transparent"
          onClick={() => {
            if (!drag) onSelectStop(null);
          }}
        />

        {/* Ghost slots. Same small-dot style in both modes; the snapped one
            (cursor's nearest) gets a prominent ring with fill so the user
            sees exactly where the drop will land. */}
        {ghosts.map((g) => {
          const isOver =
            over?.kind === 'ghost' &&
            Math.abs(over.row - g.row) < EPS &&
            Math.abs(over.col - g.col) < EPS;
          if (isOver) {
            return (
              <circle
                key={`g-${fmt(g.row)},${fmt(g.col)}`}
                cx={g.col * PITCH}
                cy={g.row * PITCH}
                r={RADIUS - 1}
                fill="rgba(26,78,168,0.18)"
                stroke="#1a4ea8"
                strokeWidth={2}
                pointerEvents="none"
              />
            );
          }
          return (
            <circle
              key={`g-${fmt(g.row)},${fmt(g.col)}`}
              cx={g.col * PITCH}
              cy={g.row * PITCH}
              r={3}
              fill="rgba(255,255,255,0.85)"
              stroke="rgba(0,0,0,0.4)"
              strokeWidth={1.25}
              pointerEvents="none"
            />
          );
        })}

        {/* Stops */}
        {stops.map((s) => {
          const line = lines[s.lineId];
          const selected = selectedLineId === s.lineId;
          const isSource = drag?.source.kind === 'stop' && drag.source.lineId === s.lineId;
          const isSwapTarget =
            over?.kind === 'stop' &&
            Math.abs(over.row - s.row) < EPS &&
            Math.abs(over.col - s.col) < EPS;
          return (
            <g
              key={`s-${s.lineId}`}
              data-cell-row={s.row}
              data-cell-col={s.col}
              data-cell-kind="stop"
              data-line-id={s.lineId}
              onPointerDown={(e) => {
                if (e.button !== 0) return;
                startDrag(e, { kind: 'stop', lineId: s.lineId, row: s.row, col: s.col });
              }}
              onContextMenu={(e) => {
                e.preventDefault();
                onSelectStop(s.lineId);
                onRotateStop(s.lineId);
              }}
              style={{
                cursor: isSource && drag?.isDragging ? 'grabbing' : 'grab',
                opacity: isSource && drag?.isDragging ? 0.4 : 1,
              }}
            >
              <circle
                cx={s.col * PITCH}
                cy={s.row * PITCH}
                r={RADIUS}
                fill={line?.color ?? '#888'}
                stroke={selected ? '#000' : isSwapTarget ? '#1a4ea8' : 'rgba(0,0,0,0.2)'}
                strokeWidth={selected || isSwapTarget ? 2 : 1}
              />
              <text
                x={s.col * PITCH}
                y={s.row * PITCH}
                textAnchor="middle"
                dominantBaseline="central"
                fontSize={12}
                fontWeight={700}
                fill="#fff"
                style={{
                  pointerEvents: 'none',
                  userSelect: 'none',
                  textShadow: '0 0 2px rgba(0,0,0,0.6)',
                }}
              >
                {ORIENTATION_GLYPH[s.orientation]}
              </text>
              <title>{`${line?.service ?? ''} at (${s.row.toFixed(3)}, ${s.col.toFixed(3)}) ${s.orientation}`}</title>
            </g>
          );
        })}

        {/* Label */}
        {(() => {
          const isSource = drag?.source.kind === 'label';
          return (
            <g
              data-cell-row={label.row}
              data-cell-col={label.col}
              data-cell-kind="label"
              onPointerDown={(e) => {
                if (e.button !== 0) return;
                startDrag(e, { kind: 'label', row: label.row, col: label.col });
              }}
              onContextMenu={(e) => {
                e.preventDefault();
                onSelectLabel();
                onRotateLabel();
              }}
              transform={`rotate(${label.rotation * 45} ${label.col * PITCH} ${label.row * PITCH})`}
              style={{
                cursor: isSource && drag?.isDragging ? 'grabbing' : 'grab',
                opacity: isSource && drag?.isDragging ? 0.4 : 1,
              }}
            >
              <circle
                cx={label.col * PITCH}
                cy={label.row * PITCH}
                r={RADIUS}
                fill="#fff"
                stroke={labelSelected ? '#000' : 'rgba(0,0,0,0.4)'}
                strokeWidth={labelSelected ? 2 : 1}
              />
              <text
                x={label.col * PITCH}
                y={label.row * PITCH}
                textAnchor="middle"
                dominantBaseline="central"
                fontSize={12}
                fontWeight={700}
                fill="#222"
                style={{ pointerEvents: 'none', userSelect: 'none' }}
              >
                L
              </text>
              <title>{`Label at (${label.row.toFixed(3)}, ${label.col.toFixed(3)}) rot ${label.rotation * 45}°`}</title>
            </g>
          );
        })()}

        {/* Anchor highlight — rendered LAST so it sits on top of any
            neighboring stops/labels that would otherwise overlap and obscure
            it. Stroke-only ring (no fill) keeps the anchor's color visible. */}
        {anchor && (
          <g pointerEvents="none">
            <circle
              cx={anchor.col * PITCH}
              cy={anchor.row * PITCH}
              r={RADIUS + 1.5}
              fill="none"
              stroke="rgba(0,0,0,0.5)"
              strokeWidth={3}
            />
            <circle
              cx={anchor.col * PITCH}
              cy={anchor.row * PITCH}
              r={RADIUS + 1.5}
              fill="none"
              stroke="#fff"
              strokeWidth={1.5}
            />
          </g>
        )}
      </svg>
    </div>
  );
}
